### ISSUE TITLE
Serialized Error: ERR_MODULE_NOT_FOUND in Vitest

### ISSUE THREAD

**Issue by aleksi-magner** [kennardy/vue-yandex-metrika#6]
При попытке импорта именно если в проекте для тестов используется vitest, ваш пакет падает из-за того, что в разных файлах при импортах не указано расширение ".js". Возмоно из-за того, что файлов с одинаковым именем несколько (скрипт и декларация). Локально добавил везде в импортах расширение ".js" и проблема ушла. В других пакетах такого нет

```
FAIL  tests/x.spec.ts [ tests/x.spec.ts ]
Error: Cannot find module '/home/user/projects/node_modules/yandex-metrika-vue3/src/empty-ya' imported from /home/user/projects/node_modules/yandex-metrika-vue3/src/index.js
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
Serialized Error: { code: 'ERR_MODULE_NOT_FOUND', url: 'file:///home/user/projects/node_modules/yandex-metrika-vue3/src/empty-ya' }
```

Это же касается и других файлов - helpers, config и прочих

Моки модуля не помогают, подает на первом же импорте любого метода , например при:
```import { initYandexMetrika } from 'yandex-metrika-vue3';```

Ошибка появляется после обновления пакета ^1.2.2 → ^1.3.0

Описание проблемы: https://bobbyhadz.com/blog/javascript-error-err-module-not-found-cannot-find-module

**Comment by kennardy** [comment]
Здравствуйте, ошибка исправлена в версии 1.3.1, благодарю за помощь :)
